### DISCUSSION TITLE
Using giscus for comments in Hugo

### DISCUSSION THREAD

**Discussion by giscus** [cdwilson/cdwilson.dev#1] [Articles]
# Using giscus for comments in Hugo

After looking into a [couple](https://getreplybox.com/) [different](https://talk.hyvor.com/) [hosted](https://fastcomments.com/) [options](https://commento.io/) for enabling comments on this site, I decided to give [giscus](https://giscus.app/) a try.  

This article describes why I chose giscus and how to set it up in a Hugo site.

https://cdwilson.dev/articles/using-giscus-for-comments-in-hugo/

**Comment by cdwilson** [comment]
Let's see if this works 🤞

**Reply by cdwilson** [reply]
Looks like it's working 🎉

**Comment by rlove** [comment]
Thank you, I am closer to getting my blog setup now.

**Comment by gilben1** [comment]
Thanks for this writeup! 

I was able to take a good amount from this in setting up Giscus on [my own blog](https://gilbertdev.net/posts/2023/02/from-disqus-to-giscus/).

**Comment by HCY-ASLEEP** [comment]
Thank you very much!

This also inspires me to use giscus withe hugo-papermod-theme on my [blog](https://hcy-asleep.github.io/)!

**Comment by SZRabinowitz** [comment]
I only have one issue with Giscus. It bothers me that the comment button is at the bottom of all the comments. If anyone has ideas let me know

**Reply by kemitix** [reply]
I'm struggling to even get mine to even show, but I think set setting you want to change is `inputPosition = "bottom"`.

**Reply by SZRabinowitz** [reply]
yes I finally found it in the github issues, thanks. 

What are you struggling on?

**Reply by kemitix** [reply]
I couldn't get the form to even appear. I'm using the Loveit theme, so I should be able to just set some parameters in the `config.toml` to enabled it.
```toml
#  Comment config    
[params.page.comment]
  enable = true
[params.page.comment.giscus]
  # You can refer to the official documentation of giscus to use the following configuration.
  enable = true
  repo = "********"
  repoId = "*******"
  category = "Announcements"
  categoryId = "********"
  # automatically adapt the current theme i18n configuration when empty
  lang = ""
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lazyLoading = false
  lightTheme = "light"
  darkTheme = "dark"
```
